config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'

  resources :topics do
    member do
      post 'upvote'
      post 'downvote'
    end
  end


end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  validates :title, :description, presence: true


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController <ApplicationController

  def index
    @topics = Topic.all
    @topics = @topics.sort_by{ |p| p.votes.count }.reverse
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path, notice: "Topic '#{@topic.title}' was successfully created!"
    else
      flash[:notice] = "Please check your topic and try again!"
      render 'new'
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "Topic Updated!"
    end
    redirect_to topics_path
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end


  def downvote
    @topic = Topic.find(params[:id])
    if @topic.votes.count >0
      @topic.votes.last.destroy
      redirect_to(topics_path)
    else
      flash[:notice] = "Unable to downvote '#{@topic.title}' anymore!"
      redirect_to(topics_path)
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="flash-msg">
  <%= flash[:notice] %>
</div>
<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
    <%= form_for @topic do |f| %>
    <ul>
      <% @topic.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %><br/>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %><br/>
    </p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>

<p><%= link_to 'Back to Topics', topics_path %>

app/views/topics/edit.html.erb
<h1>Edit a Topic</h1>
<%= render 'form' %>

app/views/topics/index.html.erb
<h1>All Topics</h1>

<table>
  <tr>
    <th>Title</th>
  </tr>
  <% @topics.each do |topic| %>
    <tr>
      <td><%= link_to topic.title, topic %></td>
      <td><%= pluralize(topic.votes.count, 'vote') %></td>
      <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
      <td><%= button_to '-1', downvote_topic_path(topic), method: :post %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Create a New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<h1>Show Topic</h1>


<p><strong>Title: </strong><%= @topic.title %></p>
<p><strong>Description: </strong><%= @topic.description%></p>

<p><%= link_to 'Back to Topics', topics_path %> | <%= link_to 'Edit Topic', edit_topic_path %> | <%= link_to 'Delete Topic', topic_path(@topic), data: {confirm: "Are you sure you want to delete '#{@topic.title}'?"}, method: :delete %></p>